version: "3.0"

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  markdown_doc:
    run: r:latest -e 'rmarkdown::render("analysis/markdown_report.Rmd", output_dir = "output")'
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        report: output/markdown_report.html